Frontend: Difficulty Selection/Home Page
CS3219-AY2223S1/cs3219-project-ay2223s1-g28 pull request #5
Opened 2022-09-04 04:06 UTC by hsiaojietng

Frontend of the home page where users can select the difficulty of their interview coding question.

Homepage:
![image](https://user-images.githubusercontent.com/56862300/190936222-d6cb3931-1a68-43bd-8c74-0af32271f9f3.png)

2022-09-14 01:39 UTC, hsiaojietng commented on user-service/controller/user-controller.js
> +            localStorage.setItem('token', token);
I will create Github Issue for this function

2022-09-15 00:07 UTC, DesmondTo commented on user-service/controller/user-controller.js
> +            localStorage.setItem('token', token);
I think it's done by lixue already no worries

2022-09-15 00:37 UTC, DesmondTo requested changes

2022-09-15 00:37 UTC, DesmondTo commented on frontend/src/components/PrivateRoute.js
> +    return !localStorage.getItem('token') ? <Navigate to='/signin' /> : <Outlet />;
Hi, can you help us do a favor here thanks.

1. Create a new route in user-service that use the authenticateJwt function defined by lixue, can return a response telling you whether the token is valid. 

2. Then, in this file here you can send a GET request to user-service along with the cookie stored, using axios.

Refer to [this stackoverflow](https://stackoverflow.com/questions/43002444/make-axios-send-cookies-in-its-requests-automatically) to see how to do that.

3. The the res.success returned is true you navigate them to outlet, else to signin page

2022-09-19 07:05 UTC, closed without merging

2022-09-19 07:06 UTC, hsiaojietng commented
Original forked repo has some issues, thus I created another repo to fork the main project. This PR is linked to the previous repo that has issues, hence I will close this PR.